mongoSettings:
  databaseName: "tesodev-go"
  uri: "mongodb://admin:admin@127.0.0.1:27017"
rabbitConfig:
  host: "127.0.0.1"
  port: 5672
  virtualHost: "/"
  connectionName: "go-rabbitmq-consumer-app"
  username: "guest"
  password: "guest"
queuesConfig:
  order:
    logCreated:
      exchange: "Log-Order-Exchange"
      exchangeType: "fanout"
      routingKey: ""
      queue: "Log-Order-Queue"
    orderDeleted:
      exchange: "Customer-Exchange"
      exchangeType: "direct"
      routingKey: "Deleted-Customer-Queue"
      queue: "Deleted-Customer-Queue"